### ISSUE TITLE
Import several pages from wiki

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-software-manual#10]
Import from wiki:
- [x] http://robots.uc3m.es/index.php/TEO_Diagrams -> https://github.com/roboticslab-uc3m/teo-software-manual/blob/master/appendix/a-teo-diagrams.md
- [x] http://robots.uc3m.es/index.php/Procedimiento_Demos -> New page

Help: Workflow described [here](https://github.com/asrob-uc3m/tutoriales/issues/2#issue-273074070)

**Comment by jgvictores** [comment]
Blocking https://github.com/roboticslab-uc3m/teo-main/issues/15

**Comment by rsantos88** [comment]
mmm... this is [the result](https://github.com/roboticslab-uc3m/teo-software-manual/blob/issue%2310/appendix/a-teo-diagrams.md) using `pandoc`, following the workflow...
I think... it's necessary to do it manually..

**Comment by jgvictores** [comment]
Yes, for diagrams it will look much better manually.

**Comment by rsantos88** [comment]
done [here](https://github.com/roboticslab-uc3m/teo-software-manual/pull/20)

**Comment by jgvictores** [comment]
Great!
Just update the originals (http://robots.uc3m.es/index.php/TEO_Diagrams etc) and feel free to close!

**Comment by rsantos88** [comment]
updated!

**Comment by jgvictores** [comment]
http://robots.uc3m.es/index.php/Procedimiento_Demos ? :smile:

**Comment by jgvictores** [comment]
Updated http://robots.uc3m.es/index.php/Procedimiento_Demos
