### ISSUE TITLE
restore important wiki information

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/teo-software-manual#14]
There have been changes in the wiki where important information has been deleted:
http://robots.uc3m.es/index.php?title=TEO&diff=next&oldid=2750

Important to restore:
> CuiAbsolute: VirtualBox Image with Windows 7 and MPLAB IDE v8.92, Documentation.

**Comment by rsantos88** [comment]
Do you want to export [this](http://robots.uc3m.es/index.php/CuiAbsolute_Documentation) page to a `.md` file and include it in this repository?

**Comment by jgvictores** [comment]
That would be great!

**Comment by rsantos88** [comment]
done at (ceef3b31c60198a5159eddaaffa1120ddfd8b665)

**Comment by jgvictores** [comment]
Cool, essentially what had been lost was CuiAbsolute:
- [https://drive.google.com/a/uc3m.es/folderview?id=0BxR76I90oKSmdnRhQlpsS3pXWm8&usp=sharing VirtualBox Image with Windows 7 and MPLAB IDE v8.92]
- [[CuiAbsolute Documentation|Documentation]]. -> imported at ceef3b31c60198a5159eddaaffa1120ddfd8b665.

**Comment by jgvictores** [comment]
> [https://drive.google.com/a/uc3m.es/folderview?id=0BxR76I90oKSmdnRhQlpsS3pXWm8&usp=sharing VirtualBox Image with Windows 7 and MPLAB IDE v8.92]

Incorporated info at 1ffe43001115ffff6c05a73727a5fee02c8da3dd

> [[CuiAbsolute Documentation|Documentation]]. -> imported at ceef3b3.

Linked from manipulation and locomotion at same commit, 1ffe43001115ffff6c05a73727a5fee02c8da3dd

**Comment by jgvictores** [comment]
Merged into `master` at ee838c71dc2d7befe18889dc531db3fd660d3e5f.

@rsantos88 Thanks a lot! Feel free to close this issue!!
