### ISSUE TITLE
Not all manual files being installed

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-software-manual#16]
Not all files being installed since aprox b2515c9f50c30c811e9207e6f6aacaba09260149.

Maybe time to rethink if installation is really required (or perhaps do not think solving is worth the time to invest).

**Comment by PeterBowman** [comment]
All files being installed again at https://github.com/roboticslab-uc3m/teo-developer-manual/commit/13024a3ae1706e897352330a1a9c0e7ef9082962, CMake was complaining about a missing directory (`appendix` was recently renamed).

> Maybe time to rethink if installation is really required (or perhaps do not think solving is worth the time to invest).

Given that we pull this repo in the teo-main superbuild, it might make sense if we ever use CPack and distribute everything together: binaries, development libraries and headers, and **documentation** (Doxygen + these manuals).
