### ISSUE TITLE
Check for wikilink

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-software-manual#21]
Check for orphan `wikilink` from imports.

**Comment by jgvictores** [comment]
Some done at 209ab31eaa44eed26ffd1f4657f74823d217c3d1

**Comment by PeterBowman** [comment]
All `wikilink` occurrences seem to have been replaced ([search results](https://github.com/roboticslab-uc3m/teo-developer-manual/search?q=wikilink&unscoped_q=wikilink)). Can we close this?

**Comment by jgvictores** [comment]
Ok, closing!
