### ISSUE TITLE
Update b-teo-network-information.md

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/teo-software-manual#24]
Several *teo-body* string occurrences [in here](https://github.com/roboticslab-uc3m/teo-software-manual/blob/8789d4c4975bd5d00748ee1227ecb3b04851b5a3/appendix/b-teo-network-information.md).

Related: roboticslab-uc3m/yarp-devices#99.

**Comment by jgvictores** [comment]
Done as of https://github.com/roboticslab-uc3m/teo-developer-manual/commit/1cbf99ecd8455ee5e5d28c1aa93fc5c2016686bd.
