### ISSUE TITLE
Add schematics of Teo boards as reference

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-software-manual#29]
_From @David-Estevez on March 9, 2017 10:8_

Add schematics of Teo boards in PDF to this repo as reference for Teo users. 

I'm working with Pedro on this one.

_Copied from original issue: roboticslab-uc3m/teo-hardware-manual#18_

**Comment by PeterBowman** [comment]
Not doint, this info will land on https://github.com/roboticslab-uc3m/teo-electronics instead.
