### ISSUE TITLE
Request: accessible hardware documentation for robot users

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-software-manual#31]
_From @David-Estevez on February 24, 2017 19:0_

During the incidents described in #3  we had a difficult time figuring what the correct connections were for some of Teo boards.

To avoid further damage, it would also had been very useful to have the schematics (and later modifications) of those boards, to ensure that hardware hotfixes don't break more than they fix.

I propose the creation of an updated hardware reference guide / repository with all these resources.

(Migrated from https://github.com/roboticslab-uc3m/teo-body/issues/96)

_Copied from original issue: roboticslab-uc3m/teo-hardware-manual#4_

**Comment by PeterBowman** [comment]
See:
- https://github.com/roboticslab-uc3m/datasheets-and-manuals
- https://github.com/roboticslab-uc3m/teo-electronics/

Added at https://github.com/roboticslab-uc3m/teo-developer-manual/commit/7fce09418a7442ec1bc44e2bd31f5e932b19dd92.
