### ISSUE TITLE
Strange things in teo-link-names.pdf

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-software-manual#35]
Strange things in [teo-link-names.pdf](https://github.com/roboticslab-uc3m/teo-developer-manual/blob/6e711465f7b0db7f6d023e7f714b131e414bba11/assets/teo-link-names.pdf)
- Duplicate AxialWaist and FrontalWaist

@AlvaroMartinezR Help plz! : )

**Comment by AlvaroMartinezR** [comment]
Didn't realize the mistake, I will fix it.

**Comment by jgvictores** [comment]
Another question, do you usually pre-pend Left/Right? Maybe this could be  explicit in the drawing?

**Comment by AlvaroMartinezR** [comment]
Yes, I will add it too.

**Comment by jgvictores** [comment]
Thanks!!!

**Comment by AlvaroMartinezR** [comment]
Done!

**Comment by jgvictores** [comment]
Brutal!!

**Comment by AlvaroMartinezR** [comment]
For the record, the pdf file was edited using xournal and the font is CenturyGothic.
