### ISSUE TITLE
Import info on MBED hand controller

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-software-manual#36]
Import info on MBED hand controller, such as: https://github.com/roboticslab-uc3m/yarp-devices/issues/172#issuecomment-373329796

**Comment by PeterBowman** [comment]
Not sure what we actually want to import, the sources are now hosted at https://github.com/roboticslab-uc3m/jr3-mbed-firmware/ (see https://github.com/roboticslab-uc3m/yarp-devices/issues/263).

**Comment by jgvictores** [comment]
I'd say:
- [x] firmware: https://github.com/roboticslab-uc3m/jr3-mbed-firmware/
- [x] schematics: https://github.com/roboticslab-uc3m/teo-electronics/

So closing!
