### ISSUE TITLE
Document installation of FCL for ubuntu 14.04

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/teo-software-manual#37]
Are [this](https://github.com/roboticslab-uc3m/installation-guides/blob/master/install-openrave.md) installation guide for Openrave updated?
Where is FCL installation for ubuntu 14.04 [here](https://github.com/roboticslab-uc3m/installation-guides/blob/master/install-openrave.md#install-openrave-with-fcl-confirmed-for-ubuntu-1504-1510-1610-1704)?

**Comment by PeterBowman** [comment]
1. Should be, at least more up-to-date than the ones I used long ago: [1](http://fsuarez6.github.io/blog/openrave-trusty/), [2](http://fsuarez6.github.io/blog/workstation-setup-xenial/).
2. Look at [*ref1, trusty, see next link if still in trouble with FCL*](https://github.com/roboticslab-uc3m/installation-guides/blob/9e10dce89fbe654b63b79d00c371b04401025ed7/install-openrave.md#external-installation-tutorialscript-links), which brings you back to the same website.

**Comment by jgvictores** [comment]
> Are [this](https://github.com/roboticslab-uc3m/installation-guides/blob/master/install-openrave.md) installation guide for Openrave updated?

Yes, our latest version is definitely at `master` to which you link, 0fc5817181bf3fa6eef4d07b18f5a70091297da4 ATOW.

> Where is FCL installation for ubuntu 14.04 [here](https://github.com/roboticslab-uc3m/installation-guides/blob/master/install-openrave.md#install-openrave-with-fcl-confirmed-for-ubuntu-1504-1510-1610-1704)? 

Yes, FCL is in a separate section as it is not mandatory. If you confirm the guide works for 14.04 (iin fact, it should) you can add it to the section name. : )

**Comment by jgvictores** [comment]
This issue was moved to roboticslab-uc3m/installation-guides#45
