### ISSUE TITLE
Move the links to download the image of virtualbox

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/teo-software-manual#39]
Do you think [this](https://github.com/roboticslab-uc3m/teo-developer-manual/blob/master/appendix/c-teo-network-information.md#manipulation-additional-setup) is a good place to find the image to be able to reprogram the encoders? (TEO Network Information?)
Maybe I think is better to move it in the end of [this](https://github.com/roboticslab-uc3m/teo-developer-manual/blob/master/overview/firmware.md) page.
Do you think the same?

**Comment by rsantos88** [comment]
Note: The image has been updated with `EasySetUp ` for tunning drivers (dcab8e5983bccc29f77f5802ade3be3d5080b0a5)

**Comment by PeterBowman** [comment]
Let's stick with it ([current location](https://github.com/roboticslab-uc3m/teo-developer-manual/blob/56d31448d15751b87ad63e1849be530e5d81c9d9/network-information.md#manipulation-install)).
