### ISSUE TITLE
Update state of PCs

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-software-manual#42]
Update state of PCs.

- https://github.com/roboticslab-uc3m/teo-main/issues/32 involved a migration from Debian 6.0 to Ubuntu 14.04 on TEO.
- Also: https://github.com/roboticslab-uc3m/teo-developer-manual/issues/23
- The issue of the PC that used to be called teo-main will be treated separately at #41

**Comment by jgvictores** [comment]
Done at 226daba9df46ca2809760f422e89e8cc2a5d15f8 and 50c8020d4d0e675f33587e2415db6f64f230927a

**Comment by PeterBowman** [comment]
According to @rsantos88, TEO's manipulation and locomotion PC's run Xenial (16.04) while teo-head hosts Ubuntu 15.xx.

**Comment by jgvictores** [comment]
> According to @rsantos88, TEO's manipulation and locomotion PC's run Xenial (16.04) while teo-head hosts Ubuntu 15.xx.

Okay, I've updated the info at 89092a2!
