### ISSUE TITLE
Add Driver Check Procedure

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-software-manual#47]
Add Driver Check Procedure

**Comment by jgvictores** [comment]
Probably in wiki (thus dupe) but would like to raise priority on this specific task

**Comment by PeterBowman** [comment]
Done at https://github.com/roboticslab-uc3m/teo-developer-manual/commit/4b5d14fb39bee8d9e74d6b4bbbedecde46f1f52b.
