### ISSUE TITLE
Update switches picture and procedure to turn on

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-software-manual#48]
Update switches picture and procedure to turn on

**Comment by rsantos88** [comment]
Changes: https://github.com/roboticslab-uc3m/teo-developer-manual/pull/57
Any way you can render/visualize the changes in this branch to see it?

**Comment by PeterBowman** [comment]
>  Any way you can render/visualize the changes in this branch to see it?

In https://github.com/roboticslab-uc3m/teo-developer-manual/pull/57/files, click on the "..." and view file.

**Comment by rsantos88** [comment]
mmm... is not that. I mean to visualize the change in the rendering of the gitbook

**Comment by rsantos88** [comment]
I understand that the only way you can render the changes is to download the repository, position yourself in the branch and render it locally.

**Comment by jgvictores** [comment]
Closed by @rsantos88 via https://github.com/roboticslab-uc3m/teo-developer-manual/pull/57 merged at https://github.com/roboticslab-uc3m/teo-developer-manual/commit/1d46801c15b018298ce2fcd5a16f58fefc7a28ce THANKS!!!!

**Comment by jgvictores** [comment]
PS: Link to rendered page: http://robots.uc3m.es/gitbook-teo-developer-manual/switches-and-power.html
