### ISSUE TITLE
[RTM] Update demo procedure

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-software-manual#49]
Update demo procedure: Cleanup to leave https://github.com/roboticslab-uc3m/teo-developer-manual/issues/48 plus basics, then delegate to individual demo repos.

**Comment by rsantos88** [comment]
Updated via #60

**Comment by jgvictores** [comment]
Oh! RTM=Ready To Merge? :rofl:

**Comment by rsantos88** [comment]
yeah!

**Comment by jgvictores** [comment]
Merged https://github.com/roboticslab-uc3m/teo-developer-manual/pull/60, thanks!!!

**Comment by jgvictores** [comment]
PS: Minor fixes added at https://github.com/roboticslab-uc3m/teo-developer-manual/commit/9969ba4e8a238bd7a9cd968fd5a1932b26d447d6 :smile:

**Comment by rsantos88** [comment]
Perfect! Thank you :)
