### ISSUE TITLE
Review motores-motores vs motores-transmision

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-software-manual#51]
Review motores-motores vs motores-transmision

**Comment by jgvictores** [comment]
Blocks #52

**Comment by rsantos88** [comment]
no more blocking: 8134447ee0c6b1aba966944df7d565da36d0cdd4
You can do pull request: https://github.com/roboticslab-uc3m/teo-developer-manual/pull/53

**Comment by jgvictores** [comment]
Fixed with https://github.com/roboticslab-uc3m/teo-developer-manual/pull/53 at https://github.com/roboticslab-uc3m/teo-developer-manual/commit/253c71925abfe7d58e48eae775ed5617abcedd4d
