### ISSUE TITLE
motores.ods: split max/mins, remove units

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-software-manual#52]
motores.ods: split max/mins, remove units

Blocked by #51

**Comment by rsantos88** [comment]
pull request https://github.com/roboticslab-uc3m/teo-developer-manual/pull/53

**Comment by jgvictores** [comment]
Fixed with https://github.com/roboticslab-uc3m/teo-developer-manual/pull/53 at https://github.com/roboticslab-uc3m/teo-developer-manual/commit/253c71925abfe7d58e48eae775ed5617abcedd4d
