### ISSUE TITLE
Link broken to CuiAbsolute Documentation

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/teo-software-manual#55]
In http://robots.uc3m.es/gitbook-teo-developer-manual/network-information.html link to [CuiAbsolute Documentation](https://github.com/roboticslab-uc3m/teo-developer-manual/blob/master/cui-absolute-values.md) is broken

**Comment by jgvictores** [comment]
Fixed via https://github.com/roboticslab-uc3m/teo-developer-manual/commit/b35f1ffd97716e8ec2db909052d947e89cef0d0b, sorry about that!!!
