### ISSUE TITLE
The link of Tutorials is broken in http://robots.uc3m.es

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/teo-software-manual#56]
The link of [Tutorials](http://asrob.uc3m.es/index.php/Tutoriales) is broken in http://robots.uc3m.es
(Move this issue if this is not the correct place to post it)

**Comment by jgvictores** [comment]
Fixed via http://robots.uc3m.es/index.php?title=Main_Page&type=revision&diff=2806&oldid=2803 !!
