### ISSUE TITLE
Review YARP ids in locomotion

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/teo-software-manual#62]
See [motores-motores.csv](https://github.com/roboticslab-uc3m/teo-developer-manual/blob/5b9f6ac3e53ef8b39ae3bd45f9847c89ccca899e/csv/motores-motores.csv) (and original .ods file). Ids assigned to leg joints range from 1 to 6, should start at zero instead.

By the way, no head joints?

**Comment by jgvictores** [comment]
Done at https://github.com/roboticslab-uc3m/teo-developer-manual/commit/493e37e327f3beaafd1a6d121c426dcc7e94abbb

**Comment by PeterBowman** [comment]
Using *Neck* as head joint names because we might want to install different head types in the future (several necks? neck + eyes?).
