### ISSUE TITLE
Gitbook generation breaking

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-software-manual#70]
Gitbook generation breaking and thus not updated in the render, apparently since Apr 6, 2022 ([first breaking commit](https://github.com/roboticslab-uc3m/teo-developer-manual/commit/e89e63a8e1a5d383338b68611c2f57999c9dd5e4)). This is not due to contents, but from due to the [`include-csv`](https://github.com/roboticslab-uc3m/teo-developer-manual/blob/5454fba14a8a10cbcc4d77b02db57af426ccf3b0/book.json#L5), as seen in the [log](https://github.com/roboticslab-uc3m/teo-developer-manual/actions/runs/5716008416/job/15486559230) (note that this log is erased with time):

```bash
info: install plugin "include-csv" (*) from NPM with version 1.0.1 
/root/.gitbook/versions/3.2.3/node_modules/npm/node_modules/aproba/index.js:25
    if (args[ii] == null) throw missingRequiredArg(ii)
```

**Comment by PeterBowman** [comment]
Related: https://github.com/roboticslab-uc3m/docker-gitbook/issues/1.

**Comment by PeterBowman** [comment]
Not doing, we have migrated to MkDocs at https://github.com/roboticslab-uc3m/teo-developer-manual/commit/2ece46b3152fc78c805f2d736708a28c04b21842.
